version: "2.1"
services:
  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    cap_add:
    - NET_ADMIN
    - SYS_MODULE
    environment:
    - PUID=1000
    - PGID=1000
    # - TZ=Asia/Tehran
    - SERVERURL="167.235.57.192" # domain optional, public IP is required at least
    - SERVERPORT=51820
    - PEERS=3 # number of peers
    - PEERDNS=auto #optional
    volumes:
    - /lib/config:/config
    - /lib/modules:/lib/modules
    ports:
    - 51820:51820/udp
    sysctls:
    - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
